# MySQL - 5.x
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cyberengine_production
  pool: 5
  username: cyberengine
  password: cyberengine
  host: localhost
  port: 3306

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cyberengine_development
  pool: 5
  username: cyberengine
  password: cyberengine
  host: localhost
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cyberengine_test
  pool: 5
  username: cyberengine
  password: cyberengine
  host: localhost
  port: 3306