# MySQL - 5.x
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: scoringengine_production
  pool: 5
  username: scoringengine
  password: scoringengine
  host: localhost
  port: 3306

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: scoringengine_development
  pool: 5
  username: scoringengine
  password: scoringengine
  host: localhost
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: scoringengine_test
  pool: 5
  username: scoringengine
  password: scoringengine
  host: localhost
  port: 3306