source 'https://rubygems.org'

gem 'activesupport'
gem 'activerecord'
gem 'bluepill'

# SSH Login
gem 'net-ssh'


# Database options
gem 'pg' # PostgreSQL by default
# gem 'mysql2' # MySQL
# gem 'sqlite3' # Sqlite3
